- targets:
  - '13.233.186.92:9100'
  labels:
    environment: 'prod'
    host: 'jeet-mq'

- targets:
  - '13.203.150.231:9100'
  labels:
    environment: 'prod'
    host: 'jeet-pre'

- targets:
  - '43.205.236.69:9100'
  labels:
    environment: 'prod'
    host: 'jeet-ck'

- targets:
  - '3.111.59.211:9100'
  labels:
    environment: 'prod'
    host: 'jeet-api'

- targets:
  - '13.126.88.54:9100'
  labels:
    environment: 'prod'
    host: 'yj777-pre'

- targets:
  - '13.235.189.106:9100'
  labels:
    environment: 'prod'
    host: 'yj777-api'

- targets:
  - '13.201.70.220:9100'
  labels:
    environment: 'prod'
    host: 'yj777-ck'

- targets:
  - '65.2.30.241:9100'
  labels:
    environment: 'prod'
    host: 'yj777-mq'

- targets:
  - '3.110.175.145:9100'
  labels:
    environment: 'prod'
    host: 'u77-mq'

- targets:
  - '13.200.169.26:9100'
  labels:
    environment: 'prod'
    host: 'u77-pre'

- targets:
  - '65.1.236.10:9100'
  labels:
    environment: 'prod'
    host: 'u77-api'

- targets:
  - '43.205.230.236:9100'
  labels:
    environment: 'prod'
    host: 'u77-ck'

- targets:
  - '13.202.250.103:9100'
  labels:
    environment: 'prod'
    host: 'asgame-pre'

- targets:
  - '13.127.233.235:9100'
  labels:
    environment: 'prod'
    host: 'asgame-mq'

- targets:
  - '13.127.10.205:9100'
  labels:
    environment: 'prod'
    host: 'asgame-api'

- targets:
  - '13.201.60.141:9100'
  labels:
    environment: 'prod'
    host: 'asgame-ck'

- targets:
  - '65.2.189.9:9100'
  labels:
    environment: 'prod'
    host: 'ez777-ck'

- targets:
  - '13.127.5.44:9100'
  labels:
    environment: 'prod'
    host: 'ez777-pre'

- targets:
  - '35.154.225.58:9100'
  labels:
    environment: 'prod'
    host: 'ez777-api'

- targets:
  - '3.108.193.29:9100'
  labels:
    environment: 'prod'
    host: 'ez777-mq'

- targets:
  - '13.127.127.75:9100'
  labels:
    environment: 'prod'
    host: 'slotinr-pre'

- targets:
  - '13.201.115.53:9100'
  labels:
    environment: 'prod'
    host: 'slotinr-mq'

- targets:
  - '3.110.120.112:9100'
  labels:
    environment: 'prod'
    host: 'slotinr-ck'

- targets:
  - '65.2.84.98:9100'
  labels:
    environment: 'prod'
    host: 'slotinr-api'

- targets:
  - '13.201.143.126:9100'
  labels:
    environment: 'prod'
    host: 'RR9-pre'

- targets:
  - '13.234.31.192:9100'
  labels:
    environment: 'prod'
    host: 'RR9-mq'

- targets:
  - '3.6.1.33:9100'
  labels:
    environment: 'prod'
    host: 'RR9-api'

- targets:
  - '13.126.202.126:9100'
  labels:
    environment: 'prod'
    host: 'RR9-ck'

- targets:
  - '43.204.155.159:9100'
  labels:
    environment: 'prod'
    host: '1bt-pre'

- targets:
  - '13.235.244.11:9100'
  labels:
    environment: 'prod'
    host: '1bt-mq'

- targets:
  - '65.2.166.157:9100'
  labels:
    environment: 'prod'
    host: '1bt-ck'

- targets:
  - '13.202.238.96:9100'
  labels:
    environment: 'prod'
    host: '1bt-api'

- targets:
  - '3.108.39.111:9100'
  labels:
    environment: 'prod'
    host: 'luckybet-pre'

- targets:
  - '13.200.172.109:9100'
  labels:
    environment: 'prod'
    host: 'luckybet-api'

- targets:
  - '13.235.134.213:9100'
  labels:
    environment: 'prod'
    host: 'luckybet-mq'

- targets:
  - '15.206.146.81:9100'
  labels:
    environment: 'prod'
    host: 'luckybet-ck'

- targets:
  - '3.110.156.193:9100'
  labels:
    environment: 'prod'
    host: 'YY6-mq'

- targets:
  - '15.206.110.122:9100'
  labels:
    environment: 'prod'
    host: 'YY6-pre'

- targets:
  - '3.111.39.247:9100'
  labels:
    environment: 'prod'
    host: 'YY6-ck'

- targets:
  - '13.202.201.121:9100'
  labels:
    environment: 'prod'
    host: 'YY6-api'

- targets:
  - '13.127.7.68:9100'
  labels:
    environment: 'prod'
    host: 'A8888-api'
- targets:
  - '13.235.55.211:9100'
  labels:
    environment: 'prod'
    host: 'A8888-ck'
- targets:
  - '13.202.81.127:9100'
  labels:
    environment: 'prod'
    host: 'A8888-mq'
- targets:
  - '3.108.38.153:9100'
  labels:
    environment: 'prod'
    host: 'A8888-pre'